apiVersion: apps/v1

kind: Deployment
metadata:
    name: ftps-deployment
    labels:
        app   : ftps
spec:
    replicas: 1
    selector:
        matchLabels:
            project: ftps
    template:
        metadata:
            labels:
                project: ftps
                app     : ftps
        spec:
            containers:
                - name: ftps
                  image: alpine-ftps
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 21
                      - containerPort: 21000
---
apiVersion: v1

kind: Service
metadata:
    name: ftps-service
    annotations:
        metallb.universe.tf/allow-shared-ip: shared
    labels:
        app: ftps
        env: ft_services
spec:
    type: LoadBalancer
    selector:
        project: ftps
    ports:
        - name: ftps
          port: 21 
        - name: ftpsd0
          port: 21000
